Risks: Risks
Risk: Risk
Locations: Locations
Location: Location
ManufacturingStandards: Manufacturing standards
ManufacturingStandard: Manufacturing standard
PumpLayouts: Layouts
PumpLayout: Layout
PumpClasses: Pump classes
PumpClass: Pump class
PumpOrientations: Pump orientations
PumpOrientation: Pump orientation
NoDataYet: No data yet
PumpTypes: Pump types
PumpType: Pump type
SurveySheet: Survey sheet
Participant: Participant

Undo: Undo
PasswordChanged: Password changed
PasswordDoesNotMatch: The password does not match
RepeatPassword: Repeat password
PasswordChange: Password change
UploadPhoto: Upload photo
TakePhoto: Take a photo
FullName: Full name
ThankYou: Thank you
All: All
Theme: Theme
UserAccount: User account
Profile: Profile
SuperuserCannotBeDeleted: Superuser cannot be deleted
DataAdministrator: Data administrator
UserRoles: User roles
AccessDeniedManagerOrAdminOnly: Only Event Managers and Data Administrators have access to this page. Please log in as an Event Manager or Data Administrator
Manager: Manager
NumberSign: ##
Superuser: Superuser
Overview: Overview
UseCaseDiagram: Use Case Diagram
AnotherAccountAccessProhibited: Access to another user's account is prohibited
EmailAddress: Email address
Message: Message
MessageSubject: Subject
Header: Header
SendEmail: Send Email
Send: Send
Value: Value
NewField: New field
AddField: Add field
List: List
RegistrationDate: Date of registration
IssueDate: Issue date
Subscribers: Subscribers
Registration: Registration
Register: Register
Time: Time
Events: Events
Event: Event
Next: Next
Previous: Previous
Sun: Sun
Sat: Sat
Fri: Fri
Thu: Thu
Wed: Wed
Tue: Tue
Mon: Mon
Calendar: Calendar
Stop: Stop

IssueTracking: Issue tracking
Timeout: Timeout
Find: Find
Radius: Radius
MainMenu: Main menu
Type: Type
Brand: Brand
Phone: Phone
OpeningHours: Opening hours
Address: Address
Search: Search
Landmark: Landmark
Close: Close
Tooltip: Tooltip
Duration: Duration
EndDate: End date
StartDate: Start date
Chart: Chart
Action: Action
Timestamp: Timestamp
Hours: Hours
DurationHours: Duration
Remarks: Remarks
StateMachineDiagram: State machine diagram
BasicEntities: Basic entities
NotAuthorized: Not authorized
SignInToAccessPlease: Please sign in to access this page
LoginToAccessPlease: Please login to access this page
Statistics: Statistics
Owner: Owner
Sequence: Sequence
End: End
Start: Start
LoginForMoreDetailsPlease: Please login for more details
WelcomeTo: Welcome to
ChangePassword: Change password
AlreadyExists: Already exists
No: No
Yes: Yes
DemoUserAccounts: Demo user accounts
User: User
Administrator: Administrator
InvalidUrlOrRemoved: Invalid URL or resource removed
Authentication: Authentication
Or: or
Back: Back
BackToHomepage: Go back to homepage
InvalidArguments: Invalid arguments
PermissionDenied: Permission denied
PageNotFound: Page not found
PleaseAddIfNecessary: Please add if necessary
Empty: Empty
Copy: Copy
Settings: Settings
Country: Country
CountryRU: RU
CountryUS: US
Language: Language
LangRu: Russian
LangEn: English
Create: Create
Link: Link
Attribution: Attribution
Logo: Logo
Photo: Photo
Url: URL
Details: Details
Title: Title
RecordDeleted: Record deleted
InvalidFormData: Invalid form data
DateCreated: Date created
TimeCreated: Time created
Author: Author
SourceCode: Source code
GitHub: GitHub
EntityRelationshipDiagram: Entity relationship diagram
Documentation: Documentation
Description: Description
Name: Name
RecordEdited: Record edited
RecordAdded: Record added
Edit: Edit
DeleteAreYouSure: Are you sure you want to delete?
ConfirmPlease: Please confirm
Actions: Actions
Homepage: Home page
MenuButton: Menu button
Save: Save
Cancel: Cancel
Dele: Delete
Change: Change
Add: Add
NoData: No data
NothingToShow: Nothing to show
EmptyDataSet: Empty dataset
AccessDeniedAdminsOnly: Only administrators have access to this page. Please log in with an administrator account
LoginPlease: Please log in
Users: Users
Email: E-mail
ResetPassword: Reset password
RestoreLogin: Restore login
Password: Password
Username: Username
SignOut: Sign out
SignIn: Sign in
Home: Home
MetaDescription: Create and manage Survey Sheets
AppName: Pumps

Doc000: Create and manage Survey Sheets
Doc001 appname@Text href@Text: <a class="link" href=#{href} target=_blank>#{appname}</a> allows to create and manage survey sheets.
Doc002 href@Text: <a class="link" href=#{href} target=_blank>Project repository</a> on GitHub.
Doc003 href@Text: Please note that the application currently running is a demo application. Any actions are allowed and encouraged. <a class="link" href=#{href} target=_blank>Report issues</a> on GitHub.
Doc004: A superuser account is defined at deployment time. The superuser manages other users and grants or revokes administrator privileges to specific users.
Doc005: Integration with external APIs
Doc006: An event manager can create events, send notifications, assign participants only to those events that he manages.
Doc007: Data administrators have full access to all events and data.