Parameters: Параметры
Parameter: Параметр
Subsections: Подразделы
ParentSection: Родительский раздел
Sections: Разделы
Section: Раздел
OfferDate: Предложение, дата
ResponsibleFilling: Ответственный, Заполнение
ResponsibleExecutor: Ответсвенный, Исполнитель
CustomerEmail: E-mail заказчика
CustomerPhone: Телефон заказчика
ResponsibleCustomer: Ответственный, Заказчик
CompletionDate: Срок окончания
ProcedureEndDate: Срок окончания процедуры
ProcedureStartDate: Срок начала процедуры
ElectricMotorInfo: Информация об электродвигателе
BasicInformationAboutTheElectricMotor: Основная информация об электродвигателе
Flanges: Фланцы
DesignFeatures: Конструктивные особенности
DesignFeaturesOfThePump: Конструктивные особенности насоса
TechnicalInformation: Техническая информация
TechnicalInformationAboutThePump: Техническая информация о насосе
PumpedLiquid: Перекачиваемая жидкость
BasicInformationAboutThePumpedLiquid: Основная информация о перекачиваемой жидкости
BasicInformation: Основная информация
ServicePart: Служебная часть
Customer: Заказчик
Quantity: Количество
DateOfFilling: Дата заполнения
PumpPositionCode: Код позиции (насоса)
ProcedureNumber: Номер процедуры
Symbol: Символ
UnitsOfMeasurement: Единицы измерения
UnitOfMeasurement: Единица измерения 
Risks: Риски
Risk: Риск
Locations: Размещения
Location: Размещение
ManufacturingStandards: Стандарты изготовления
ManufacturingStandard: Стандарт изготовления
PumpLayouts: Компоновки
PumpLayout: Компоновка
PumpClasses: Классы насосов
PumpClass: Класс насоса
PumpOrientations: Ориентации насоса
PumpOrientation: Ориентация насоса
NoDataYet: Данных пока нет
PumpTypes: Типы насосов
PumpType: Тип насоса
SurveySheet: Опросный лист
SurveySheets: Опросные листы
Participants: Участники
Participant: Участник

Undo: Отменить
PasswordChanged: Пароль изменен
PasswordDoesNotMatch: Пароль не совпадает
RepeatPassword: Повторите пароль
PasswordChange: Смена пароля
UploadPhoto: Загрузить фото
TakePhoto: Сфотографироваться
FullName: Полное имя
ThankYou: Спасибо
All: Все
Theme: Тема
UserAccount: Учетная запись пользователя
Profile: Профиль
SuperuserCannotBeDeleted: Суперпользователя нельзя удалить
DataAdministrator: Администратор данных
UserRoles: Роли пользователей
AccessDeniedManagerOrAdminOnly: Доступ к этой странице имеют только менеджеры мероприятий и администраторы данных. Пожалуйста, войдите в систему как менеджер событий или администратор данных
Manager: Менеджер
NumberSign: №
Superuser: Суперпользователь
Overview: Обзор
UseCaseDiagram: Диаграмма вариантов использования
AnotherAccountAccessProhibited: Доступ к учетной записи другого пользователя запрещен
EmailAddress: Адрес электронной почты
Message: Сообщение
MessageSubject: Тема
Header: Заголовок
SendEmail: Отправить электронное письмо
Send: Отправить
Value: Значение
NewField: Новое поле
AddField: Добавить поле
List: Список
RegistrationDate: Дата регистрации
IssueDate: Дата выпуска
Subscribers: Подписчики
Registration: Регистрация
Register: Зарегистрировать
Time: Время
Events: События
Event: Событие
Next: Следующий
Previous: Предыдущий
Sun: вс
Sat: сб
Fri: пт
Thu: чт
Wed: ср
Tue: вт
Mon: пн
Calendar: Календарь
Stop: Остановить

IssueTracking: Отслеживание ошибок
Timeout: Тайм-аут
Find: Найти
Radius: Радиус
MainMenu: Главное меню
Type: Тип
Brand: Бренд
Phone: Телефон
OpeningHours: Часы работы
Address: Адрес
Search: Поиск
Landmark: Достопримечательность
Close: Закрыть
Tooltip: Подсказка
Duration: Продолжительность
EndDate: Дата окончания
StartDate: Дата начала
Chart: Диаграмма
Action: Действие
Timestamp: Временная метка
Hours: Часы
DurationHours: Продолжительность
Remarks: Замечания
StateMachineDiagram: Схема машины состояний
BasicEntities: Базовые сущности
NotAuthorized: Не разрешено
SignInToAccessPlease: Пожалуйста, войдите в систему, чтобы получить доступ к этой странице
LoginToAccessPlease: Пожалуйста, войдите в систему, чтобы получить доступ к этой странице
Statistics: Статистика
Owner: Владелец
Sequence: Последовательность
End: Конец
Start: Начало
LoginForMoreDetailsPlease: Пожалуйста, войдите в систему для более подробной информации
Welcome: Добро пожаловать
WelcomeTo: Добро пожаловать на
ChangePassword: Изменить пароль
AlreadyExists: Уже существует
No: Нет
Yes: Да
DemoUserAccounts: Демо-аккаунты
User: Пользователь
Administrator: Администратор
InvalidUrlOrRemoved: Неверный URL-адрес или ресурс удален
Authentication: Аутентификация
Or: или
Back: Вернуться
BackToHomepage: Вернуться на домашнюю страницу
InvalidArguments: Неверные аргументы
PermissionDenied: Доступ запрещен
PageNotFound: Страница не найдена
PleaseAddIfNecessary: Пожалуйста, добавьте, если необходимо
Empty: Пустой
Copy: Копировать
Settings: Настройки
Country: Страна
CountryRU: Россия
CountryUS: США
Language: Язык
LangRu: Русский
LangEn: Английский
Create: Создать
Link: Ссылка
Attribution: Атрибуция
Logo: Логотип
Photo: Фото
Url: URL-адрес
Details: Подробности
Title: Название
RecordDeleted: Запись удалена
InvalidFormData: Неверные данные формы
DateCreated: Дата создания
TimeCreated: Время создания
Author: Автор
SourceCode: Исходный код
GitHub: GitHub
EntityRelationshipDiagram: Диаграмма взаимосвязи сущностей
Documentation: Документация
Description: Описание
Name: Имя
RecordEdited: Запись отредактирована
RecordAdded: Запись добавлена
Edit: Редактировать
DeleteAreYouSure: Вы уверены, что хотите удалить?
ConfirmPlease: Пожалуйста подтвердите
Actions: Действия
Homepage: Домашняя страница
MenuButton: Кнопка меню
Save: Сохранить
Cancel: Отмена
Dele: Удалить
Change: Изменить
Add: Добавить
NoData: Нет данных
NothingToShow: Нечего показывать
EmptyDataSet: Пустой набор данных
AccessDeniedAdminsOnly: Доступ к этой странице имеют только администраторы. Пожалуйста, войдите под учетной записью администратора
LoginPlease: Пожалуйста, войдите в систему
Users: Пользователи
Email: Электронная почта
ResetPassword: Сбросить пароль
RestoreLogin: Восстановить вход
Password: Пароль
Username: Логин
SignOut: Выйти
SignIn: Войти
Home: Главная
MetaDescription: Создание и управление листами опроса
AppName: Насосы

Doc000: Создание и управление листами опроса
Doc001 appname href: <a class="link" href=#{href} target=_blank>#{appname}</a> позволяет создавать и управлять листами опроса.
Doc002 href: <a class="link" href=#{href} target=_blank>Репозиторий проекта</a> на GitHub.
Doc003 href: Обратите внимание, что приложение, работающее в данный момент, является демонстрационным. Любые действия разрешены и поощряются. <a class="link" href=#{href} target=_blank>Сообщайте об ошибках</a> на GitHub.
Doc004: Учетная запись суперпользователя определяется во время развертывания. Суперпользователь управляет другими пользователями и предоставляет или отзывает права администратора конкретным пользователям.
Doc005: Интеграция с внешними API
Doc006: Менеджер мероприятий может создавать мероприятия, отправлять уведомления, назначать участников только на те мероприятия, которыми он управляет.
Doc007: Администраторы данных имеют полный доступ ко всем данным и могут предоставлять или отзывать права администратора другим пользователям.